#$UPN = "AccountName"
#$fname = "FirstName"
#$sname = "SurName"
#$company = "Company"
#$department "Department"
#$title = "Title"
#$manager = "Manager"
#$Path = "OU=Super,dc=anssi,dc=local"

$UPN = "Taina"
$fname = "Taina"
$sname = "Tainanen"
$company = "Free"
$department = "Her"
$title = "Goddess"
$manager = "admin"
$description = "Taina"
$Path = "OU=Super,dc=anssi,dc=local"

$UPN = "Miia"
$fname = "Miia"
$sname = "Vihainen"
$company = "so angry"
$department = "sänky"
$title = "sleepyhead"
$manager = "admin"
$description = "Niin vihainen saliskippaaja"
$Path = "OU=Kiosk,dc=anssi,dc=local"

New-ADUser $UPN -AccountPassword (Read-Host -AsSecureString "AccountPassword") -Department $department -GivenName $fname -Surname $sname -title $title -Company $company -manager $manager -description $description -Path $path -UserPrincipalName $UPN -PasswordNeverExpires $true -ChangePasswordAtLogon $false -enabled $true